### ISSUE TITLE
Crash when using on pylint's functional test

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [hakancelik96/unimport#103]
Hello, thank you for this projet, I was trying to add it to pylint's codebase. I encountered a crash on the following code snipper (at least I think so):

```python
"""Checks that disabling 'wrong-import-position' on a statement prevents it from
invalidating subsequent imports."""
# pylint: disable=unused-import

CONSTANT = True  # pylint: disable=wrong-import-position

import sys
```
Result:
```
Traceback (most recent call last):
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/bin/unimport", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/unimport/__main__.py", line 203, in main
    refactor_source = session.refactor_file(py_path, apply=True)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/unimport/session.py", line 79, in refactor_file
    result = self.refactor(source)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/unimport/session.py", line 69, in refactor
    refactor = refactor_string(
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/unimport/refactor.py", line 155, in refactor_string
    fixed_module = wrapper.visit(
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/metadata/wrapper.py", line 207, in visit
    return self.module.visit(visitor)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/module.py", line 91, in visit
    result = super(Module, self).visit(visitor)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/module.py", line 75, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/internal.py", line 200, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/internal.py", line 172, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/statement.py", line 424, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/internal.py", line 156, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/internal.py", line 140, in visit_iterable
    new_child = child.visit(visitor)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_nodes/base.py", line 234, in visit
    leave_result = visitor.on_leave(self, with_updated_children)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/libcst/_visitors.py", line 71, in on_leave
    updated_node = leave_func(original_node, updated_node)
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/unimport/refactor.py", line 132, in leave_ImportFrom
    return self.leave_StarImport(
  File "/home/pierre/.cache/pre-commit/repof33_opx7/py_env-python3/lib/python3.8/site-packages/unimport/refactor.py", line 98, in leave_StarImport
    if imp.modules:
AttributeError: 'NoneType' object has no attribute 'modules'
```

If this can't be reproduced with the snippet, you can probably reproduce with `pre-commit install;pre-commit run --all-files` on this branch : https://github.com/Pierre-Sassoulas/pylint/tree/add-unimport-to-pre-commit-configuration (https://github.com/Pierre-Sassoulas/pylint/commit/e05cac9daa83ff7fe98e61e9a5979653393cb165)

**Comment by hakancelik96** [comment]
@hadialqattan The `get_star_imp` function does not always return a result, this error is caused by the line we deleted recently.

We just must have missed writing the test for this case.

**Comment by hadialqattan** [comment]
> @hadialqattan The `get_star_imp` function does not always return a result, this error is caused by the line we deleted recently.
> 
> We just must have missed writing the test for this case.

I'm sorry about that!

**Comment by hakancelik96** [comment]
@Pierre-Sassoulas Hello, it's an honor for me. Thank you for opening this issue, thanks to you, I found a difficult case to find and fixed it. I've done some tests for Pylint and haven't seen any other issues.

**Comment by Pierre-Sassoulas** [comment]
Haha, yeah I'm not surprised, pylint's functional tests are full of dysfunctional code example ;) Thank you for pre-screening on pylint !
