### ISSUE TITLE
Unimport 0.9.1 is broken

### ISSUE THREAD

**Issue by WouldYouKindly** [hakancelik96/unimport#196]
Hello!

I've just updated to 0.9.1 and got this error
```
$ unimport
Traceback (most recent call last):
  File "/Users/alexey.popov/.virtualenvs/doge/bin/unimport", line 33, in <module>
    sys.exit(load_entry_point('unimport==0.9.1', 'console_scripts', 'unimport')())
  File "/Users/alexey.popov/.virtualenvs/doge/bin/unimport", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/alexey.popov/.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/alexey.popov/.pyenv/versions/3.9.1/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'unimport'
```

Reproduced in a fresh venv, Python 3.9.1

**Comment by drewbrew** [comment]
Replicated on 3.6.8 here

**Comment by drewbrew** [comment]
It looks like the flaw is in the packaging, not the code itself:

```
% tar xvzf unimport-0.9.1.tar.gz
x unimport-0.9.1/
x unimport-0.9.1/LICENSE
x unimport-0.9.1/PKG-INFO
x unimport-0.9.1/README.md
x unimport-0.9.1/setup.cfg
x unimport-0.9.1/setup.py
x unimport-0.9.1/unimport.egg-info/
x unimport-0.9.1/unimport.egg-info/PKG-INFO
x unimport-0.9.1/unimport.egg-info/SOURCES.txt
x unimport-0.9.1/unimport.egg-info/dependency_links.txt
x unimport-0.9.1/unimport.egg-info/entry_points.txt
x unimport-0.9.1/unimport.egg-info/not-zip-safe
x unimport-0.9.1/unimport.egg-info/requires.txt
x unimport-0.9.1/unimport.egg-info/top_level.txt
```

The `unimport` package is missing from the tarball on PyPI.

Compare that to the contents of 0.9.0's tarball (17 kB vs 3.5 kB):

```
% tar xvzf unimport-0.9.0.tar.gz
x unimport-0.9.0/
x unimport-0.9.0/LICENSE
x unimport-0.9.0/MANIFEST.in
x unimport-0.9.0/PKG-INFO
x unimport-0.9.0/README.md
x unimport-0.9.0/setup.cfg
x unimport-0.9.0/setup.py
x unimport-0.9.0/unimport/
x unimport-0.9.0/unimport/__init__.py
x unimport-0.9.0/unimport/__main__.py
x unimport-0.9.0/unimport/analyzer.py
x unimport-0.9.0/unimport/color.py
x unimport-0.9.0/unimport/config.py
x unimport-0.9.0/unimport/constants.py
x unimport-0.9.0/unimport/emoji.py
x unimport-0.9.0/unimport/main.py
x unimport-0.9.0/unimport/refactor.py
x unimport-0.9.0/unimport/relate.py
x unimport-0.9.0/unimport/statement.py
x unimport-0.9.0/unimport/utils.py
x unimport-0.9.0/unimport.egg-info/
x unimport-0.9.0/unimport.egg-info/PKG-INFO
x unimport-0.9.0/unimport.egg-info/SOURCES.txt
x unimport-0.9.0/unimport.egg-info/dependency_links.txt
x unimport-0.9.0/unimport.egg-info/entry_points.txt
x unimport-0.9.0/unimport.egg-info/not-zip-safe
x unimport-0.9.0/unimport.egg-info/requires.txt
x unimport-0.9.0/unimport.egg-info/top_level.txt
```

**Comment by hakancelik96** [comment]
It seems that there are some issues that I missed in the setup file.

https://github.com/hakancelik96/unimport/commit/5ccac669b933ec1ae11badb6a848e0da7876e79b

**Comment by hakancelik96** [comment]
https://pypi.org/project/unimport/0.9.2/

**Comment by drewbrew** [comment]
Confirmed, 0.9.2 works for me.

Thanks so much!

**Comment by hakancelik96** [comment]
You are welcome

**Comment by WouldYouKindly** [comment]
@hakancelik96 Thank you very much. 

By the way, there is a trick to avoid this situation: put your project under `/src`: https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure. `attrs` is a great example: https://github.com/python-attrs/attrs/tree/main/src/attr. It's author, Hynek, also has a blog post on advantages of /src approach.
