### ISSUE TITLE
Unimport crushes when more than one star import exist on the same file.

### ISSUE THREAD

**Issue by hadizakialqattan** [hakancelik96/unimport#84]
**\_\_main\_\_.py** file:
```shell
> cat __main__.py
from time import *
from os import *

time()  # Function from time module.
path.join()  # Function from os module
```
as you see we have two star imports.

**unimport** behavior:
```
> unimport __main__.py --include-star --diff
Traceback (most recent call last):
  File "/usr/local/bin/unimport", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/unimport/__main__.py", line 192, in main
    exists_diff = print_if_exists(session.diff_file(py_path))
  File "/usr/local/lib/python3.8/dist-packages/unimport/session.py", line 93, in diff_file
    result = self.refactor_file(path, apply=False)
  File "/usr/local/lib/python3.8/dist-packages/unimport/session.py", line 79, in refactor_file
    result = self.refactor(source)
  File "/usr/local/lib/python3.8/dist-packages/unimport/session.py", line 69, in refactor
    refactor = refactor_string(
  File "/usr/local/lib/python3.8/dist-packages/unimport/refactor.py", line 132, in refactor_string
    fixed_module = wrapper.visit(
  File "/usr/local/lib/python3.8/dist-packages/libcst/metadata/wrapper.py", line 207, in visit
    return self.module.visit(visitor)
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/module.py", line 91, in visit
    result = super(Module, self).visit(visitor)
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/module.py", line 75, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/internal.py", line 200, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/internal.py", line 172, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/statement.py", line 424, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/internal.py", line 156, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/internal.py", line 140, in visit_iterable
    new_child = child.visit(visitor)
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/base.py", line 234, in visit
    leave_result = visitor.on_leave(self, with_updated_children)
  File "/usr/local/lib/python3.8/dist-packages/libcst/_visitors.py", line 71, in on_leave
    updated_node = leave_func(original_node, updated_node)
  File "/usr/local/lib/python3.8/dist-packages/unimport/refactor.py", line 115, in leave_ImportFrom
    return self.leave_StarImport(
  File "/usr/local/lib/python3.8/dist-packages/unimport/refactor.py", line 81, in leave_StarImport
    names_to_suggestion.append(cst.ImportAlias(cst.Name(module)))
  File "<string>", line 6, in __init__
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/base.py", line 115, in __post_init__
    self._validate()
  File "/usr/local/lib/python3.8/dist-packages/libcst/_nodes/expression.py", line 353, in _validate
    raise CSTValidationError("Name is not a valid identifier.")
libcst._nodes.base.CSTValidationError: Name is not a valid identifier.
```
as you see `unimport` crushes when I used `--include-star` & `--diff` options!

**Script to check the behavior (Linux):**
```shell
#!/bin/bash
printf "from time import *\nfrom os import *\n\ntime()\npath.join()\n" > __main__.py
cat __main__.py
unimport __main__.py --include-star --diff
rm __main__.py
```

**Comment by hakancelik96** [comment]
I fixed this issue, can you try again with the final commit.

**Comment by hadizakialqattan** [comment]
Good job!

**unimport** new behavior:
```shell
> unimport __main__.py

--- __main__.py

+++

@@ -1,5 +1,5 @@

-from time import *
-from os import *
+from time import time
+from os import path

 time()
 path.join()
```
